# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - CasperWMS

on:
  push:
    branches:
      - project
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies (backend)
        working-directory: aweb-project/backend
        run: npm install


      - name: Build backend (if applicable)
        working-directory: aweb-project/backend
        run: npm run build --if-present


      - name: Run backend tests (if available)
        working-directory: aweb-project/backend
        run: npm run test --if-present


      - name: Zip backend artifact
        working-directory: aweb-project/backend
        run: |
          zip -r ../backend_release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: aweb-project/backend_release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Download artifact for deployment
        uses: actions/download-artifact@v4
        with:
          name: backend-app


      - name: Unzip artifact for deployment
        run: unzip backend_release.zip


      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F9FD467B71AA4388B227E78FA88053E4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_210BDA72E8A241F59C48D377150BB09C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7A254B4DF277432E8BF9D932754D52BD }}


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CasperWMS'
          slot-name: 'Production'
          package: .
